### ISSUE TITLE
Module 'ngCordovaOauth' is not available after new release ngCordova 0.1.18-alpha

### ISSUE THREAD

**Issue by nielskrijger** [nraboy/ng-cordova-oauth#114] opened 2015-08-04 08:12 UTC
Not sure if this problem was caused due to ngCordova or something in ngCordovaOauth. 

Basically this morning our builds started to fail with the following error:

```
Module 'ngCordovaOauth' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

This was caused due to a new release of ngCordova 0.1.18-alpha. For now we've downgraded to 0.1.17-alpha and it works properly again.

I don't have more details atm.

See also
https://github.com/driftyco/ng-cordova/issues/901

Feel free to close this issue if it is unrelated to ng-cordova-oauth; hope this helps others experiencing the same issue.

**Comment by pppglowacki** [comment] 2015-08-04 11:07
We also have the same issue. Our fix was to go back to .14

**Comment by matheusrocha89** [comment] 2015-08-04 11:49
When this happen in your CI? What command your CI do to get the `ngCordova` it clones the project or just download the release?

**Comment by nielskrijger** [comment] 2015-08-04 11:59
@matheusrocha89 It is not CI-specific, I was able to reproduce the issue when reinstalling all dependencies on my local machine as well.

ngCordova is installed using bower install both locally and on CI.

**Comment by matheusrocha89** [comment] 2015-08-04 12:01
The problem is that the new build of ngCordova does not package the `ngCordovaOauth` I saw here on the code, I will open an issue on `ngCordova`

**Comment by matheusrocha89** [comment] 2015-08-04 12:04
Open! :)

**Comment by nielskrijger** [comment] 2015-08-04 12:10
@matheusrocha89 Thanks for the update! We'll wait for a new release before upgrading.

Link to the issue: https://github.com/driftyco/ng-cordova/issues/912

**Comment by matheusrocha89** [comment] 2015-08-04 12:19
@nielskrijger I think it was already fix it, on the next release of `ngCordova` the problem will be solved https://github.com/driftyco/ng-cordova/pull/909

**Comment by matheusrocha89** [comment] 2015-08-04 12:20
You could try to download the dev version on master branch and test it just to see if it works.

**Comment by gortok** [comment] 2015-08-04 12:46
Resolved with v0.1.19-alpha tag.

**Comment by nraboy** [comment] 2015-08-04 12:58
The submodule itself is fine.  The problem was Gulp.  I was doing some reading and all that reading points to Gulp 3.x being awful.  Asynchronous events in Gulp are a common problem of 3.x and the internet claims 4.0 corrects this.

**Closed by nraboy** 2015-08-04 12:58 UTC

**Comment by gortok** [comment] 2015-08-04 13:17
@nraboy That's good to know.
