### ISSUE TITLE
Cordova Oauth linkedin error "Sign in flow was cancelled"

### ISSUE THREAD

**Issue by jackmasi** [nraboy/ng-cordova-oauth#249] opened 2016-05-11 14:07 UTC
I am following the Cordova Oauth procedure to get the access token, But after the login success i am always getting "Sign in flow was cancelled". I am using from android mobile. I register developer account in linkedin. Please help me to resolve the issues.
 
My Code:

 $cordovaOauth.linkedin("75**********y", "b**********4", ["r_basicprofile"],    "7*********a").then(function(result) {
            	alert("accesstoken result");
            },function(error) {
                alert("accesstoken error "+error);
             
            });

**Comment by nraboy** [comment] 2016-05-11 15:54
How did you make your configurations in the LinkedIn dashboard?  My guess is that it is a configuration issue, as the oauth APIs have not changed.

**Comment by jackmasi** [comment] 2016-05-12 13:39
i Just register and got the clientid and clientsecret information. 
Client ID:	75d8o3s1zzueiy
 Client Secret:	bBAkSZSRBxNW0YM4

I checked all the Default Application Permissions
r_basicprofile	r_emailaddress	rw_company_admin
w_share

In the OAuth 2.0 i just add the Authorized Redirect URL is   "http://localhost/callback"
 
finally i click update. This is the configuration done by me. Other than this i didnt changed nothing.  But error throwing as "the sign in flow was cancelled"

**Comment by priya-sookshum-labs** [comment] 2016-05-13 14:28
I am too getting the same error same configuartion as @jackmasi 
looks like linkedIn authentication doesn't need Client Secret ID
![image](https://cloud.githubusercontent.com/assets/18184930/15250991/f9e945e6-1944-11e6-8089-e0cd4715497c.png)

**Comment by priya-sookshum-labs** [comment] 2016-05-13 14:30
I am getting the same error and the configuration are same as @jackmasi 
and I found out LinkedIn doesn't need a Client Secret Id for authentication [https://developer.linkedin.com/docs/oauth2](url)

**Comment by nraboy** [comment] 2016-05-13 15:41
I just tested and it works fine for me:

![linkedin-oauth](https://cloud.githubusercontent.com/assets/983958/15253208/2d1c5836-18e6-11e6-894c-c12004ea3b9b.png)

This goes in combination with the following code:

```
$scope.linkedin = function() {
        $cordovaOauth.linkedin("CLIENT_ID_HERE", "CLIENT_SECRET_HERE", ["r_basicprofile", "r_emailaddress"], "nraboy-test").then(function(result) {
            console.log("RESPONSE -> " + JSON.stringify(result));
        }, function(error) {
            console.log("ERROR -> " + JSON.stringify(error));
        });
    }
```

To answer @priya-sookshum-labs question, we are using a secret because when I created the library, LinkedIn only supported explicit grants.  Are you saying LinkedIn now supports implicit grants?

I am closing this ticket as there is no reproducible problem.

Best,

**Closed by nraboy** 2016-05-13 15:41 UTC

**Comment by priya-sookshum-labs** [comment] 2016-05-13 16:05
@nraboy Thank you for your time and work, my problem is solved I created a new app in LinkedIn and used this combination  ["r_basicprofile", "r_emailaddress"] , before I tested on ["r_basicprofile"] and
 ["r_basicprofile", "r_emailaddress", rw_company_admin] and using the combination you provided code working now.
About the implicit grants Linked I read the doc so linked didn't mention anywhere that the Client Secret is required so I am not sure, was just curious as a beginner anyway thank you so much for your time :)

**Comment by nraboy** [comment] 2016-05-13 16:12
Implicit grants (client id only) are always preferred for JavaScript applications.  Not all providers offer this though.

**Comment by jackmasi** [comment] 2016-05-17 07:17
@priya-sookshum-labs I just followed your process. But again I am getting same error like "Sign in flow was cancelled". Actually i am using from my android mobile. I don't know may i missed any configuration during this process. So please give the solution for this.
My Steps:
1. I could create the new app in LinkedIn developer. And I got the client Id and Client secret.
2. I added redirect uri. And i click update.
3. Now i check from my android mobile. Now i am getting the error

**Comment by priya-sookshum-labs** [comment] 2016-05-17 07:40
@jackmasi This is my code.
  var linkedinlogin = function(){
      $ionicLoading.show({template: 'Loading...'});
      $cordovaOauth.linkedin(LinkedIn_Client_id, LinkedIn_Client_Secret, ['r_basicprofile', "r_emailaddress"], 'oauth-login-test')
      .then(function(result) {
      console.log("RESPONSE -> " + JSON.stringify(result));
        $ionicLoading.hide();
        $state.go("tab");
      },function(error){
      console.error("Unable to connect to Linkedin");
      console.log("ERROR -> " + JSON.stringify(error));
        $ionicLoading.hide();
      $state.go("login");
      });
    };

Please match the linkedin project details 
![linkedin](https://cloud.githubusercontent.com/assets/18184930/15314609/a35d26b8-1c30-11e6-8217-743b35f92ecb.jpg)

**Comment by jackmasi** [comment] 2016-05-17 08:59
I am following your comments. But still the error is continuing.

**Comment by jackmasi** [comment] 2016-05-17 09:06
@priya-sookshum-labs I am following your steps. But still the error is occuring. 
![ln reg](https://cloud.githubusercontent.com/assets/19307770/15316788/2419c04e-1c3c-11e6-9f25-7ab3034152b8.JPG)


And My Code is 

 $cordovaOauth.linkedin('755nl2m4ujzjir', 'aZlUWx7DaDgRFqF1', ['r_basicprofile', 'r_emailaddress'], 'guyky-test890')
       .then(function(result) {
    	   alert("RESPONSE -> " + JSON.stringify(result));
    	   $ionicLoading.hide();
       }, function(error) {
    	   alert("ERROR -> " + JSON.stringify(error));
    	   $ionicLoading.hide();
       });

I assume any configuration is missing where i register the developer account or need to do specific for mobile devices. So please let me know

**Comment by priya-sookshum-labs** [comment] 2016-05-17 09:53
@jackmasi Can't say What is wrong with configuration without looking at it, but did you follow this guide [https://developer.linkedin.com/docs/oauth2](url)
It might help you set the correct configuration.

**Comment by priya-sookshum-labs** [comment] 2016-05-17 10:08
@jackmasi I just ran my code with your client id and secret and I am getting successfully the access token , so looks like your configuration is correct, try adding inappbrowser plugin and platform again

**Comment by jackmasi** [comment] 2016-05-17 11:53
may i know which android version is using mobile as well as android sdk manager.
And which version inappbrowser plugin is used for developing

**Comment by priya-sookshum-labs** [comment] 2016-05-17 12:37
@jackmasi 
android mobile version : v 4.4.2,
android:minSdkVersion="16" 
android:targetSdkVersion="23"

Cordova Plugin list 

cordova-plugin-console 1.0.3 "Console"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-inappbrowser 1.4.1-dev "InAppBrowser"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
ionic-plugin-keyboard 2.2.0 "Keyboard"

Ionic info

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Version: 1.3.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS:
Node Version: v5.11.0

**Comment by noor92** [comment] 2016-09-06 09:30
hello, 

whats the solution to this issue? I have tried everything everyone suggested but it doesnt work

**Comment by jackmasi** [comment] 2016-10-19 18:15
Finally I got the accesstoken using this procedure. Thanks @nraboy

**Comment by noor92** [comment] 2016-10-26 09:21
@jackmasi  can you please tell me what you did to solve this issue ? I am still confused
