### ISSUE TITLE
Webpage not loading Facebook Login

### ISSUE THREAD

**Issue by amangijoe** [nraboy/ng-cordova-oauth#327] opened 2017-04-28 10:47 UTC
I have included everything from callback url to enabling Facebook Oauth its still showing error

**Comment by amangijoe** [comment] 2017-04-28 10:49
> 
![screenshot_20170428-161418](https://cloud.githubusercontent.com/assets/17108928/25525835/77a89ebc-2c2e-11e7-9abb-2ff1b6e3c13b.png)

**Comment by nraboy** [comment] 2017-04-28 18:12
Testing your URL in the web browser appears to work fine:

```
https://www.facebook.com/v2.6/dialog/oauth?client_id=298549003917511&redirect_uri=http://localhost
```

Your application is in development mode, but I think your device is having network problems.  I am marking this as not a bug.

If you'd like to support, you can purchase it from here:

https://www.thepolyglotdeveloper.com/hire-me/

Otherwise, feel free to use the Ionic Framework, Apache Cordova, or PhoneGap forum boards.

Best,

**Closed by nraboy** 2017-04-28 18:12 UTC
