### ISSUE TITLE
Linkedin returns "Problem authenticating" even when it's returning the token 

### ISSUE THREAD

**Issue by MarcSallent** [nraboy/ng-cordova-oauth#32] opened 2015-02-05 18:29 UTC
Hello,

I am trying to authenticate my users via Linkedin but I always get "Problem authenticating". After digging for a long time, I activated my proxy and I see that in fact I am receiving the correct data and response code in the form of

`{"access_token":"xxxxx x x x xxxx x","expires_in":5183999}`

and I can see the `200 OK` response code in the header. 

However, when I log the returned `data` in `.error(function(data, status){...` I get `null`. `.success(function(data) {...` is never called

**Comment by nraboy** [comment] 2015-02-05 20:16
So you get an $http response that contains the access token and a problem authenticating message?

Are you using ngCordovaOauth or the version I bundled with ngCordova?  Also any code you can share would be great.

It is a possibility the API changed, but it is unlikely.  Have to see whats up.

Thanks,

**Comment by MarcSallent** [comment] 2015-02-05 21:03
I am using the one bundled with ngCordova. I cannot trace the $http response, as it always resolves to .error() with all parameters empty. However, in the proxy, I see the correct (working) token sent by linkedin.

I created a new, blank project following your instructions here http://ionicframework.com/blog/oauth-ionic-ngcordova/ but it doesn't work

I could send my app credentials via private message if that's ok for you

**Comment by nraboy** [comment] 2015-02-05 21:16
Code would be preferred.  I can use my own credentials to test.

**Comment by MarcSallent** [comment] 2015-02-05 21:32
I put my index.html here https://gist.github.com/MarcSallent/c67a49852bf5d5d5d625
and the app.js here https://gist.github.com/MarcSallent/15e91d0cce8fb757c58b

I also uploaded the whole project here https://mega.co.nz/#!aFxiVaQZ!ZGix9QMOFJxUkNCX4wv3JdGKVOP9vR6rUs78VTEKL9o , but that's probably too much

Thanks

**Comment by nraboy** [comment] 2015-02-05 22:15
Your app.js is very basic and seems correct.  I'll see about testing this tonight to see if maybe the API changed.

Regards,

**Comment by MarcSallent** [comment] 2015-02-09 11:18
Hello!
Were you able to take a look at it?
Thanks!

marc

**Comment by nraboy** [comment] 2015-02-09 14:30
I haven't had a chance to look at it.  Been very busy, sorry.  Starting tomorrow (2/10) I'll be away from my computer for about two weeks.

**Comment by nraboy** [comment] 2015-02-16 19:08
I just tested again and had no issues.  Can you try using the ngCordovaOauth rather than the version I have bundled with ngCordova?

**Comment by nraboy** [comment] 2015-02-20 17:28
Closing this ticket since I cannot reproduce the problem and have not heard from the reporter.

**Closed by nraboy** 2015-02-20 17:28 UTC

**Comment by CaptainYouz** [comment] 2015-03-09 13:48
Hi guys,

i have the same problem using linkedIn. Did you look into ?
When i try to login with linkedin, the http.post request always go into the error function.

Here is my controller : 
$cordovaOauth.linkedin('PUBLIC', 'SECRET', ['r_emailaddress', 'r_network'], '0987654321')
		.then(function (result) {
			console.log('Result', JSON.stringify(result));
		}, function (error) {
			console.log('Error', error);
		});

My log : 
Problem authenticating 

And after adding log into ng-cordova.js, status equal 0 and there is no data.

**Comment by nraboy** [comment] 2015-03-09 14:27
I don't normally request for this, but can you share with me the clientId and clientSecret you're using?

I want to try to use my code to test against your registered application to see if it is an issue with how you configured your app in the LinkedIn dashboard.

When we're done, you can delete your app and register a new set of keys.

Regards,

**Comment by CaptainYouz** [comment] 2015-03-09 14:55
Ok, can i share it with you by email ?
If you dont want to share your email, here is mine : anas.mammeri@gmail.com

Thank you for your help.

**Comment by CaptainYouz** [comment] 2015-03-09 14:58
Btw, i also tried the solution you explain in this post : https://blog.nraboy.com/2014/07/using-oauth-2-0-service-ionicframework/

I still have the same error.

**Comment by nraboy** [comment] 2015-03-09 15:05
I don't use email, so you'd have to put your keys in this issue thread.

Like I said, just regenerate your keys when we're done to prevent unauthorized use.

Regards,

**Comment by CaptainYouz** [comment] 2015-03-09 15:07
Ok.
Please tell me when you have it so i can remove it.
public key = 776lurjwiaoo75
secret = mKrIO2Nid0u2h2Fe

**Comment by nraboy** [comment] 2015-03-09 15:09
I've got them.  I'll test it out tonight when I'm home and circle back.

**Comment by CaptainYouz** [comment] 2015-03-09 15:09
Thank you a lot for your time.

**Comment by nraboy** [comment] 2015-03-10 04:36
I tried with your keys, scope, and state.  I had no problems.

I have to leave this issue closed because I cannot reproduce the issue.

Regards,

**Comment by jordanvs** [comment] 2015-03-13 00:33
I'm experiencing this as well actually, has anyone solved it?

**Comment by nraboy** [comment] 2015-03-13 00:51
Can you share how to reproduce?

**Comment by jordanvs** [comment] 2015-03-14 17:14
Sure @nraboy . I created a new ionic app `ionic start myApp sidemenu`. Changed the following for the app:

- Added the last `angular.module('starter', ['ionic', 'starter.controllers', 'ngCordovaOauth'])` to app.js
- Added ng-cordova-oauth.min.js to www/js
- Added the InAppBrowser plugin
- Added the ios platform
- Added `<script src="js/ng-cordova-oauth.min.js"></script>` to index.html underneath cordova.js inclusion
- Replace the code to the boilerplate `doLogin` method in controllers.js with:

```
$cordovaOauth.linkedin('KEY', 'SECRET', ['r_basicprofile', 'r_emailaddress'], 'aowiejfoiewj').then (function (result) {
        console.log("Response Object -> " + JSON.stringify(result));
      }, function(error) {
        console.log("Error -> " + error);
      });
```
- Running using `ionic emulate ios -l -c` in iPhone 6 / iOS 8.1 simulator.

Pretty sure that's it. I have a LinkedIn app but nothing strange there. 

My problem is that I can access the LinkedIn login screen but upon pressing "Allow and Sign In" button, I get the NOT FOUND webpage and the error callback logs "Problem authenticating".

Note that I DID get my password wrong the first time I tried to log into LinkedIn (shouldn't matter but I'll state it anyway). My LinkedIn account is both an admin and developer for the app.

Thanks for the attention!

**Comment by nraboy** [comment] 2015-03-15 00:30
> Added `<script src="js/ng-cordova-oauth.min.js"></script>` to index.html underneath `cordova.js` inclusion

This is a concern.  You should be placing ng-cordova-oauth.min.js above cordova.js not underneath.

Also I encourage you to not use live-reload.  It is known to have issues with the InAppBrowser plugin.  Instead you should do `ionic build ios` and then open the project with Xcode.  From there you should be testing on the device or simulator.

Hopefully that helps.

Regards,

**Comment by jordanvs** [comment] 2015-03-15 00:37
Ok I'm going to give it a shot. Thanks Nic.

**Comment by jordanvs** [comment] 2015-03-15 00:42
Hey @nraboy thanks for the suggestions. It works now that I have taken your advice. However, I'm still seeing the Not Found webpage (/callback) before it brings me back to my app. But this is a separate issue.

**Comment by nraboy** [comment] 2015-03-15 00:52
There is a race condition with providers that have a secret key because the POST requests that happen may not finish before the callback loads.  In this scenario a page not found comes up without hurting functionality.

I've not been able to solve this problem, but I'm open to suggestions.  For implicit grant types, the problem does not exist.

Regards,

**Comment by MyBoon** [comment] 2015-04-15 18:40
Got the same problem yesterday. Running the app with browserify was leading to a CROSS error :

```sh
XMLHttpRequest cannot load linkedin.com/uas/oauth2/accessToken.
Origin http://192.168.180.139:8101 is not allowed by Access-Control-Allow-Origin.
console-via-logger.js:173
```

and **Problem authenticating** returned by *ng-cordova-oauth*.

Working like a charm if you build the ionic project and run it on your device.

**Comment by Shaolin23** [comment] 2015-04-16 19:28
I'm experiencing a similar 
error - upon submitting email and pass through the login dialog I instantly get "webView:didFailLoadWithError - -1004"

**Comment by nivil** [comment] 2015-09-18 23:34
tried with github:

```
2015-09-19 01:31:48.204 github-mobile[6087:23151801] THREAD WARNING: ['InAppBrowser'] took '75.247070' ms. Plugin should use a background thread.
2015-09-19 01:32:00.625 github-mobile[6087:23151801] webView:didFailLoadWithError - -999: The operation couldn’t be completed. (NSURLErrorDomain error -999.)
2015-09-19 01:32:00.632 github-mobile[6087:23151801] webView:didFailLoadWithError - -1004: Could not connect to the server.
```

at least auth works

**Comment by nraboy** [comment] 2015-09-19 00:12
Yea the InAppBrowser plugin is a bit wonky.  Works though :-)

**Comment by hvadotnarola** [comment] 2016-02-25 07:17
I am getting this error after getting token and trying to access data with that token.
{"errorCode":0,"message":"Mutiple authentication schemes detected","requestId":"XXXXX","status":401,"timestamp":10110101010}
can you find what is wrong with it ?
