### ISSUE TITLE
Was working, now returning nothing

### ISSUE THREAD

**Issue by chrisschaub** [nraboy/ng-cordova-oauth#75] opened 2015-05-11 20:07 UTC
So, it was all working a week ago in the device sim. I'm using the ngCordova one. And now, I authenticate, see the scopes for google, and then the screen goes away and i'm back to my app. Not a whitescreen, just back to screen with button that launched the in-app browser. Except that the response does not get returned. Is the ngCordova version more up-to-date or is this repo? Also, which inappbrowser plugin for which? Thanks.

**Comment by nraboy** [comment] 2015-05-11 20:35
That is strange.  I wonder if Google changed their APIs a bit.  Do you get any error messages?

ng-cordova-oauth will always be more up-to-date than ng-cordova.  Since it is just a side project of mine, it often becomes difficult to keep them both in sync.

Let me know.

Thanks,

**Comment by chrisschaub** [comment] 2015-05-11 20:36
No error messages. Nothing, and it was working, no errors. Can I use
ngCordova along with ng-cordova-auth? Will there be any issues with the
injected object name being the same?

On Mon, May 11, 2015 at 3:35 PM, Nic Raboy <notifications@github.com> wrote:

> That is strange. I wonder if Google changed their APIs a bit. Do you get
> any error messages?
>
> ng-cordova-oauth will always be more up-to-date than ng-cordova. Since it
> is just a side project of mine, it often becomes difficult to keep them
> both in sync.
>
> Let me know.
>
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nraboy/ng-cordova-oauth/issues/75#issuecomment-101040085>
> .
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by nraboy** [comment] 2015-05-11 20:41
I think you're going to get naming conflicts if you try to use them both.  Can you answer the following:

1. What platform(s) is it failing on?
2. What platform(s), if any, is it succeeding on?
3. How did you add the InAppBrowser to your project?
4. Are you trying to use Ionic View, Ionic Serve, or Ionic Live-Reload?
5. What version of Apache Android or Apache iOS are you using (not Apache Cordova base version)?

I know Apache has been causing me all kinds of stress with the InAppBrowser update they introduced a week or so ago.  I'm wondering if you're suffering from that.

Let me know.

Thanks,

**Comment by chrisschaub** [comment] 2015-05-11 20:45
1. I'm using ionic emulate (ios device simulator)
2. None now, but it was working on ios in the simulator.
3. I added with cordova plugin add org.apache.cordova.inappbrowser which
gets around the thread/issue of it not being found.
4. None of those. I get that it has to be on a device or sim.
5. Apache iOS? Not sure what you mean.

Thanks!

On Mon, May 11, 2015 at 3:41 PM, Nic Raboy <notifications@github.com> wrote:

> I think you're going to get naming conflicts if you try to use them both.
> Can you answer the following:
>
>    1. What platform(s) is it failing on?
>    2. What platform(s), if any, is it succeeding on?
>    3. How did you add the InAppBrowser to your project?
>    4. Are you trying to use Ionic View, Ionic Serve, or Ionic Live-Reload?
>    5. What version of Apache Android or Apache iOS are you using (not
>    Apache Cordova base version)?
>
> I know Apache has been causing me all kinds of stress with the
> InAppBrowser update they introduced a week or so ago. I'm wondering if
> you're suffering from that.
>
> Let me know.
>
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nraboy/ng-cordova-oauth/issues/75#issuecomment-101041355>
> .
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by nraboy** [comment] 2015-05-11 20:50
I believe you want to run the following:

```
cordova platform check ios
```

Should tell you which version of Apache Cordova for iOS your project is using.  Creating a fresh project will always grab the latest version, but for legacy projects, the Apache version doesn't change unless you force it.

https://cordova.apache.org/docs/en/4.0.0/guide_platforms_ios_upgrade.md.html#Upgrading%20iOS

Let me know.

Thanks,

**Comment by chrisschaub** [comment] 2015-05-11 21:16
Ahh, sorry. 3.8.0.

On Mon, May 11, 2015 at 3:50 PM, Nic Raboy <notifications@github.com> wrote:

> I believe you want to run the following:
>
> cordova platform check ios
>
> Should tell you which version of Apache Cordova for iOS your project is
> using. Creating a fresh project will always grab the latest version, but
> for legacy projects, the Apache version doesn't change unless you force it.
>
>
> https://cordova.apache.org/docs/en/4.0.0/guide_platforms_ios_upgrade.md.html#Upgrading%20iOS
>
> Let me know.
>
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nraboy/ng-cordova-oauth/issues/75#issuecomment-101043134>
> .
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by nraboy** [comment] 2015-05-12 00:47
Hey @chrisschaub 

I just did some experimenting:

1. Update NPM, Cordova, Ionic
2. Create fresh Ionic project via `ionic start IonicAuthTest blank`
3. Add Android and iOS platform via `ionic platform add android` and `ionic platform add ios`
4. Install the InAppBrowser plugin via `cordova plugin add org.apache.cordova.inappbrowser`
5. Set up ng-cordova-oauth via the instructions
6. Build for Android and iOS via `ionic build android` and `ionic build ios`
7. Install the Android and iOS binaries to the simulator

Android worked flawless.  iOS worked as well, but it also gave the following:

```
webView:didFailLoadWithError - -1004: Could not connect to the server.
```

This error doesn't seem to cause any problems.  I think an issue ticket should be raised with Apache if there isn't one already.

During my tests, I tested three providers:

* Google
* Facebook
* Imgur

With all this said, are you sure you're using ng-cordova-oauth and not ng-cordova?  I cannot reproduce your problems, but I'll remain open to more experimenting if you guide me.

Thanks,

**Comment by chrisschaub** [comment] 2015-05-12 03:29
Thanks a lot for doing that run down! I am using ng-cordova, but I'll try
to switch to ng-cordova-auth and see if that's the fix.

On Mon, May 11, 2015 at 7:47 PM, Nic Raboy <notifications@github.com> wrote:

> Hey @chrisschaub <https://github.com/chrisschaub>
>
> I just did some experimenting:
>
>    1. Update NPM, Cordova, Ionic
>    2. Create fresh Ionic project via ionic start IonicAuthTest blank
>    3. Add Android and iOS platform via ionic platform add android and ionic
>    platform add ios
>    4. Install the InAppBrowser plugin via cordova plugin add
>    org.apache.cordova.inappbrowser
>    5. Set up ng-cordova-oauth via the instructions
>    6. Build for Android and iOS via ionic build android and ionic build
>    ios
>    7. Install the Android and iOS binaries to the simulator
>
> Android worked flawless. iOS worked as well, but it also gave the
> following:
>
> webView:didFailLoadWithError - -1004: Could not connect to the server.
>
> This error doesn't seem to cause any problems. I think an issue ticket
> should be raised with Apache if there isn't one already.
>
> During my tests, I tested three providers:
>
>    - Google
>    - Facebook
>    - Imgur
>
> With all this said, are you sure you're using ng-cordova-oauth and not
> ng-cordova? I cannot reproduce your problems, but I'll remain open to more
> experimenting if you guide me.
>
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nraboy/ng-cordova-oauth/issues/75#issuecomment-101083345>
> .
>



-- 
Christopher Schaub
http://chris.schaub.com

**Comment by MWaser** [comment] 2015-05-12 12:51
Nic,

Could I get a copy of your Google test code?

Also, which simulators do you use/recommend?  (I thought that simulators were a bad idea when testing plug-ins -- am I incorrect in that?)

Thanks!

     Mark

**Comment by nraboy** [comment] 2015-05-12 14:33
I will upload my testing code to GitHub tonight or tomorrow.  You'll see it really isn't much of anything.  Just a bunch of buttons that call functions that include provider calls.

I use Genymotion for Android because it has significantly better performance than the stock Android simulator.  Both are valid simulators for testing since they mimic the actual device.

For iOS, I use Xcode.  I generally only test on the iPhone 5S simulator unless someone specifically has an issue with a different size.

It is a bad idea to use Ionic Serve, Ionic View, and Ionic Live-Reload.  They are all beta and don't give a true testing experience.  They are only a convenience.  Don't sacrifice realism for convenience.

In regards to versions.  What are you referring to?  Cordova versions, iOS versions, plugin versions, etc?

**Comment by MWaser** [comment] 2015-05-12 15:09
In regards to versions . . . . PRECISELY!  The fact that there are so many different versions potentially all interacting . . . . 

I'm biting the bullet and buying a Macbook Pro either today or tomorrow.  Any advice?

**Comment by nraboy** [comment] 2015-05-12 15:20
I code on a three year old Macbook Air 13" most of the time.  I also have a 27" iMac that I picked up a few months ago.  If you're really serious about developing on a Mac, I'd probably recommend a 15".  Sometimes I wish I had more screen on my laptop.  Spec-wise, even the lower ends should be sufficient for hybrid development.

When it comes to versions.  I just let people report issues.  I don't have the time to keep up with all the changes, and I'm lucky enough to have a lot of supportive people get me the information I need to get a fix going :).  One of the many benefits of open source!

**Comment by MWaser** [comment] 2015-05-12 16:55
:-)  I think that I have no choice but to develop on a Mac if I wish to support iPhone (is there another way to do it *effectively*)?  I was thinking of going with the 15".  I'm never happy with the amount of screen but 17" ends up being too heavy and bulky to travel . . . . (and at home I can always plug into a bigger screen -- I assume . . . . )

**Comment by nraboy** [comment] 2015-05-12 17:28
I don't know of any better way.  Sorry :-(

**Comment by MWaser** [comment] 2015-05-12 17:55
It's not your fault (and the confirmation was very helpful/reassuring).  Off to spend money I don't want to spend . . .  :-(

**Comment by nraboy** [comment] 2015-05-12 18:13
Look at it this way.  Getting a Mac will improve your productivity as a developer, stretching way beyond app development.  Native SSH, Git, etc.  A big purchase with a learning curve, but you'll like it in the end.

@chrisschaub let me know when you've given it a test.

Thanks,

**Comment by nraboy** [comment] 2015-05-14 21:19
Closing this ticket because it seems to be a non-issue.

**Closed by nraboy** 2015-05-14 21:19 UTC
